plugins:
  postcss-preset-env:
    # https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#stage
    stage: false

    # https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
    features:
      custom-media-queries: true
      media-query-ranges: true
      nesting-rules: true
      custom-selectors: true
      relative-color-syntax: true
  postcss-replace:
    # @tacc/core-styles: 'dist/' uses `../../fonts/`
    pattern: fonts/
    data:
      replaceAll: ../fonts/
