# Generated by Django 3.2.18 on 2023-08-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0001_squashed_0002_alter_staffprofileplugin_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofileplugin',
            name='name',
        ),
        migrations.AddField(
            model_name='staffprofileplugin',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofileplugin',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
