# Generated by Django 3.2.18 on 2023-08-11 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '__first__'),
        ('staff_profile', '0002_split_name_into_first_and_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofileplugin',
            name='post_nomials',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofileplugin',
            name='title2',
            field=models.CharField(max_length=100),
        ),
    ]
