# Generated by Django 3.2.18 on 2023-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0002_split_name_into_first_and_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
