# Generated by Django 3.2.18 on 2023-08-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0003_reduce_first_last_name_length_squashed_0009_do_not_require_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
