# Generated by Django 3.2.18 on 2023-08-11 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('staff_profile', '0003_reduce_first_last_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='memberships',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='research_areas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
