# Generated by Django 3.2.18 on 2023-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0004_require_only_certain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofileplugin',
            name='title2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
