# Generated by Django 3.2.18 on 2023-08-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0004_reduce_name_field_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofileplugin',
            name='experience',
        ),
    ]
