# Generated by Django 3.2.19 on 2023-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0005_remove_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='post_nomials',
            field=models.CharField(max_length=50),
        ),
    ]
