# Generated by Django 3.2.18 on 2023-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0005_add_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofileplugin',
            name='post_nomial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
