# Generated by Django 3.2.18 on 2023-08-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0006_add_field_post_nomial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofileplugin',
            old_name='post_nomial',
            new_name='post_nomials',
        ),
    ]
