# Generated by Django 3.2.18 on 2023-08-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profile', '0006_add_field_post_nomial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofileplugin',
            name='post_nomial',
        ),
        migrations.AddField(
            model_name='staffprofileplugin',
            name='post_nomials',
            field=models.CharField(blank=True, help_text='E.g. Ph.D., B.S., M.B.A.', max_length=100, verbose_name='Post-nomials'),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Group / Department'),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='description',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='first_name',
            field=models.CharField(help_text='If desired, include middle name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secondary job title'),
        ),
    ]
