# Generated by Django 3.2.18 on 2023-08-11 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('staff_profile', '0007_rename_field_post_nomial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='memberships',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='photo',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='post_nomials',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='projects',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='publications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='research_areas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='title2',
            field=models.CharField(max_length=100),
        ),
    ]
