# Generated by Django 3.2.18 on 2023-08-11 22:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('staff_profile', '0008_do_not_set_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofileplugin',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
