# Generated by Django 2.2.27 on 2023-01-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='user_news_usernewslist', serialize=False, to='cms.CMSPlugin')),
                ('max_articles', models.PositiveSmallIntegerField(blank=True, default=7, help_text='The maximum number of articles to show.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
