version: '3'
services:
  cms:
    build:
      context: ../../
      dockerfile: apps/tup-cms/Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
    container_name: tup_cms
    hostname: tup_cms
    volumes:
      - ./src/apps/portal:/code/apps/portal
      - ./src/apps/portal_nav:/code/apps/portal_nav
      - ./src/apps/staff_profile:/code/apps/staff_profile
      - ./src/apps/user_news:/code/apps/user_news
      - ./src/apps/email_management/assets:/code/apps/email_management/assets
      - ./src/media:/code/media
      - ./src/taccsite_custom:/code/taccsite_custom
      - ./src/taccsite_cms/custom_app_settings.py:/code/taccsite_cms/custom_app_settings.py
      - ./src/taccsite_cms/urls_custom.py:/code/taccsite_cms/urls_custom.py
      - ./src/taccsite_cms/settings_custom.py:/code/taccsite_cms/settings_custom.py
      - ./src/taccsite_cms/settings_local.py:/code/taccsite_cms/settings_local.py
      - ./src/taccsite_cms/secrets.py:/code/taccsite_cms/secrets.py
      - ../../dist/apps/tup-ui/imports.html:/code/taccsite_cms/templates/imports.html
      - ../../apps/tup-ui/src/assets:/code/taccsite_cms/static/src/assets
      - ../../dist/apps/tup-cms-react/assets:/code/taccsite_cms/static/cms-react/assets
      - ../../apps/tup-cms-react/imports.debug.html:/code/taccsite_cms/templates/tup-cms-react.html
    networks:
      - tup_cms_net

  postgres:
    image: postgres:14.9
    environment:
      - POSTGRES_PASSWORD=taccforever
      - POSTGRES_USER=postgresadmin
      - POSTGRES_DB=taccsite
      - PGDATA=/var/lib/postgresql/data/taccsite
    volumes:
      - tup_cms_postgres_data:/var/lib/postgresql/data
      - ./src/data:/var/tmp/data
    hostname: tup_cms_postgres
    container_name: tup_cms_postgres
    networks:
      - tup_cms_net

volumes:
  tup_cms_postgres_data:
  tup_cms_es_data:

networks:
  tup_cms_net:
